### PR TITLE
Upgraded to Ember 1.10.0, Ember Data 1.0.0-beta.15, Ember CLI 0.2.0

### PR DESCRIPTION
**Pull request by atsjj**
In addition to upgrading all three components, a minor bug was
also fixed in the article template.

Hype Train: all templates now powered by HTMLBars!

### CODE REVIEW

**Comment by chancancode** [comment]
wow! That's it?! Amazing! :heart_eyes:

**Comment by chancancode** [comment]
Does that mean we don't need to bind-attr anymore?

**Comment by atsjj** [comment]
@chancancode I think the `bind-attr` stuff is coming down in 1.11. I'll chuck a branch up on my fork and bump the version, tweak the templates and see how it runs. Probably make the boys on the core team happy if we found any bugs.

All specs went green and was working well while manually browsing stories.

BTW, loved your talk at EmberConf! Didn't get to go in person this year, but I was happy to see it on YouTube.

**Comment by chancancode** [comment]
Haha thank you!!

:+1: on beta train!

I stopped writing tests half way through because I was super rushed :( should probably back fill that now it is used as an example. Also needs better idea on testing the extractors, running it through 100s real pages seems excessive(ly slow). Or maybe separating that into its own lib would be enough.

**Pull request merged**
