### PR TITLE
Fix spelling.

### PR DESCRIPTION
**Pull request by tgxworld**

### CODE REVIEW

**Comment by chancancode** [comment]
:heart: Thank you, good to see you over here @tgxworld !

**Comment by tgxworld** [comment]
@chancancode :smile: I'm trying to pick up EmberJS so I decided to fork and see how you implemented it :smile:

**Comment by chancancode** [comment]
Let me know how it goes! Find me on hangouts/gchat if you have any questions!

**Comment by tgxworld** [comment]
@chancancode Would you recommend going with ember-rails or ember-cli? The last time I looked, ember-cli wasn't as stable. So I'm not sure where to start honestly XD

**Comment by chancancode** [comment]
Today, definitely CLI. It's a lot better now! Awesome, even!

—

**Pull request merged**
